//
//  HourlyWeatherData.swift
//  WeatherTestSwiftUITests
//
//  Created by Jack Vanderpump on 07/07/2022.
//

import Foundation

extension TestData {
    
    static let hourlyWeather = """
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    0.003,
                    51.503,
                    5.0
                ]
            },
            "properties": {
                "requestPointDistance": 1166.9907,
                "modelRunDate": "2022-07-07T21:00Z",
                "timeSeries": [
                    {
                        "time": "2022-07-07T21:00Z",
                        "screenTemperature": 19.96,
                        "maxScreenAirTemp": 21.25,
                        "minScreenAirTemp": 19.9,
                        "screenDewPointTemperature": 10.79,
                        "feelsLikeTemperature": 18.57,
                        "windSpeed10m": 3.19,
                        "windDirectionFrom10m": 127,
                        "windGustSpeed10m": 4.63,
                        "max10mWindGust": 4.77,
                        "visibility": 8750,
                        "screenRelativeHumidity": 55.12,
                        "mslp": 103160,
                        "uvIndex": 0,
                        "significantWeatherCode": 0,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-07T22:00Z",
                        "screenTemperature": 20.07,
                        "maxScreenAirTemp": 20.07,
                        "minScreenAirTemp": 19.96,
                        "screenDewPointTemperature": 10.96,
                        "feelsLikeTemperature": 19.05,
                        "windSpeed10m": 2.67,
                        "windDirectionFrom10m": 146,
                        "windGustSpeed10m": 3.62,
                        "max10mWindGust": 4.4,
                        "visibility": 7572,
                        "screenRelativeHumidity": 55.4,
                        "mslp": 103202,
                        "uvIndex": 0,
                        "significantWeatherCode": 0,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-07T23:00Z",
                        "screenTemperature": 19.33,
                        "maxScreenAirTemp": 20.07,
                        "minScreenAirTemp": 19.33,
                        "screenDewPointTemperature": 11.84,
                        "feelsLikeTemperature": 19.25,
                        "windSpeed10m": 1.52,
                        "windDirectionFrom10m": 162,
                        "windGustSpeed10m": 2.64,
                        "max10mWindGust": 3.34,
                        "visibility": 10486,
                        "screenRelativeHumidity": 61.62,
                        "mslp": 103188,
                        "uvIndex": 0,
                        "significantWeatherCode": 0,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T00:00Z",
                        "screenTemperature": 18.79,
                        "maxScreenAirTemp": 19.33,
                        "minScreenAirTemp": 18.77,
                        "screenDewPointTemperature": 11.94,
                        "feelsLikeTemperature": 19.32,
                        "windSpeed10m": 0.55,
                        "windDirectionFrom10m": 147,
                        "windGustSpeed10m": 2.18,
                        "max10mWindGust": 2.44,
                        "visibility": 11498,
                        "screenRelativeHumidity": 64.32,
                        "mslp": 103190,
                        "uvIndex": 0,
                        "significantWeatherCode": 0,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T01:00Z",
                        "screenTemperature": 18.72,
                        "maxScreenAirTemp": 18.99,
                        "minScreenAirTemp": 18.7,
                        "screenDewPointTemperature": 12.27,
                        "feelsLikeTemperature": 18.23,
                        "windSpeed10m": 2.29,
                        "windDirectionFrom10m": 316,
                        "windGustSpeed10m": 4.2,
                        "max10mWindGust": 4.58,
                        "visibility": 20123,
                        "screenRelativeHumidity": 66.17,
                        "mslp": 103190,
                        "uvIndex": 0,
                        "significantWeatherCode": 0,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T02:00Z",
                        "screenTemperature": 18.05,
                        "maxScreenAirTemp": 18.72,
                        "minScreenAirTemp": 18.04,
                        "screenDewPointTemperature": 11.98,
                        "feelsLikeTemperature": 17.77,
                        "windSpeed10m": 1.96,
                        "windDirectionFrom10m": 326,
                        "windGustSpeed10m": 3.11,
                        "max10mWindGust": 4.1,
                        "visibility": 20942,
                        "screenRelativeHumidity": 67.7,
                        "mslp": 103150,
                        "uvIndex": 0,
                        "significantWeatherCode": 0,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T03:00Z",
                        "screenTemperature": 17.34,
                        "maxScreenAirTemp": 18.05,
                        "minScreenAirTemp": 17.33,
                        "screenDewPointTemperature": 11.92,
                        "feelsLikeTemperature": 16.95,
                        "windSpeed10m": 2.13,
                        "windDirectionFrom10m": 318,
                        "windGustSpeed10m": 3.23,
                        "max10mWindGust": 3.65,
                        "visibility": 19318,
                        "screenRelativeHumidity": 70.64,
                        "mslp": 103180,
                        "uvIndex": 0,
                        "significantWeatherCode": 0,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T04:00Z",
                        "screenTemperature": 16.89,
                        "maxScreenAirTemp": 17.33,
                        "minScreenAirTemp": 16.87,
                        "screenDewPointTemperature": 11.92,
                        "feelsLikeTemperature": 16.41,
                        "windSpeed10m": 2.35,
                        "windDirectionFrom10m": 317,
                        "windGustSpeed10m": 3.36,
                        "max10mWindGust": 3.52,
                        "visibility": 17404,
                        "screenRelativeHumidity": 72.56,
                        "mslp": 103196,
                        "uvIndex": 1,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T05:00Z",
                        "screenTemperature": 16.47,
                        "maxScreenAirTemp": 16.89,
                        "minScreenAirTemp": 16.47,
                        "screenDewPointTemperature": 12.06,
                        "feelsLikeTemperature": 16.14,
                        "windSpeed10m": 2.12,
                        "windDirectionFrom10m": 325,
                        "windGustSpeed10m": 3.3,
                        "max10mWindGust": 3.64,
                        "visibility": 15309,
                        "screenRelativeHumidity": 75.14,
                        "mslp": 103222,
                        "uvIndex": 1,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T06:00Z",
                        "screenTemperature": 16.58,
                        "maxScreenAirTemp": 16.64,
                        "minScreenAirTemp": 16.47,
                        "screenDewPointTemperature": 12.11,
                        "feelsLikeTemperature": 16.56,
                        "windSpeed10m": 1.63,
                        "windDirectionFrom10m": 316,
                        "windGustSpeed10m": 2.57,
                        "max10mWindGust": 3.15,
                        "visibility": 14489,
                        "screenRelativeHumidity": 74.77,
                        "mslp": 103232,
                        "uvIndex": 1,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T07:00Z",
                        "screenTemperature": 17.56,
                        "maxScreenAirTemp": 17.58,
                        "minScreenAirTemp": 16.58,
                        "screenDewPointTemperature": 12.43,
                        "feelsLikeTemperature": 17.53,
                        "windSpeed10m": 1.72,
                        "windDirectionFrom10m": 309,
                        "windGustSpeed10m": 2.8,
                        "max10mWindGust": 2.8,
                        "visibility": 13370,
                        "screenRelativeHumidity": 71.84,
                        "mslp": 103249,
                        "uvIndex": 2,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T08:00Z",
                        "screenTemperature": 18.81,
                        "maxScreenAirTemp": 18.85,
                        "minScreenAirTemp": 17.56,
                        "screenDewPointTemperature": 12.78,
                        "feelsLikeTemperature": 18.69,
                        "windSpeed10m": 1.91,
                        "windDirectionFrom10m": 313,
                        "windGustSpeed10m": 3.55,
                        "max10mWindGust": 3.55,
                        "visibility": 17279,
                        "screenRelativeHumidity": 68.11,
                        "mslp": 103255,
                        "uvIndex": 4,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T09:00Z",
                        "screenTemperature": 20.4,
                        "maxScreenAirTemp": 20.42,
                        "minScreenAirTemp": 18.81,
                        "screenDewPointTemperature": 12.88,
                        "feelsLikeTemperature": 20.18,
                        "windSpeed10m": 2.02,
                        "windDirectionFrom10m": 310,
                        "windGustSpeed10m": 3.91,
                        "max10mWindGust": 3.91,
                        "visibility": 19573,
                        "screenRelativeHumidity": 61.95,
                        "mslp": 103255,
                        "uvIndex": 5,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T10:00Z",
                        "screenTemperature": 21.82,
                        "maxScreenAirTemp": 21.84,
                        "minScreenAirTemp": 20.4,
                        "screenDewPointTemperature": 12.59,
                        "feelsLikeTemperature": 21.52,
                        "windSpeed10m": 2.15,
                        "windDirectionFrom10m": 310,
                        "windGustSpeed10m": 4.07,
                        "max10mWindGust": 4.07,
                        "visibility": 20594,
                        "screenRelativeHumidity": 55.84,
                        "mslp": 103246,
                        "uvIndex": 6,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T11:00Z",
                        "screenTemperature": 23.27,
                        "maxScreenAirTemp": 23.29,
                        "minScreenAirTemp": 21.82,
                        "screenDewPointTemperature": 12.43,
                        "feelsLikeTemperature": 22.96,
                        "windSpeed10m": 2.2,
                        "windDirectionFrom10m": 307,
                        "windGustSpeed10m": 4.26,
                        "max10mWindGust": 4.26,
                        "visibility": 23344,
                        "screenRelativeHumidity": 50.67,
                        "mslp": 103226,
                        "uvIndex": 7,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T12:00Z",
                        "screenTemperature": 24.72,
                        "maxScreenAirTemp": 24.75,
                        "minScreenAirTemp": 23.27,
                        "screenDewPointTemperature": 11.56,
                        "feelsLikeTemperature": 24.11,
                        "windSpeed10m": 2.49,
                        "windDirectionFrom10m": 306,
                        "windGustSpeed10m": 4.74,
                        "max10mWindGust": 4.74,
                        "visibility": 25732,
                        "screenRelativeHumidity": 43.89,
                        "mslp": 103192,
                        "uvIndex": 8,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T13:00Z",
                        "screenTemperature": 25.81,
                        "maxScreenAirTemp": 25.84,
                        "minScreenAirTemp": 24.72,
                        "screenDewPointTemperature": 10.93,
                        "feelsLikeTemperature": 24.92,
                        "windSpeed10m": 2.82,
                        "windDirectionFrom10m": 309,
                        "windGustSpeed10m": 5.32,
                        "max10mWindGust": 5.32,
                        "visibility": 27355,
                        "screenRelativeHumidity": 39.57,
                        "mslp": 103153,
                        "uvIndex": 7,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T14:00Z",
                        "screenTemperature": 26.66,
                        "maxScreenAirTemp": 26.67,
                        "minScreenAirTemp": 25.81,
                        "screenDewPointTemperature": 10.78,
                        "feelsLikeTemperature": 25.67,
                        "windSpeed10m": 2.98,
                        "windDirectionFrom10m": 309,
                        "windGustSpeed10m": 5.54,
                        "max10mWindGust": 5.54,
                        "visibility": 29030,
                        "screenRelativeHumidity": 37.25,
                        "mslp": 103106,
                        "uvIndex": 6,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T15:00Z",
                        "screenTemperature": 27.33,
                        "maxScreenAirTemp": 27.34,
                        "minScreenAirTemp": 26.66,
                        "screenDewPointTemperature": 10.33,
                        "feelsLikeTemperature": 26.13,
                        "windSpeed10m": 3.23,
                        "windDirectionFrom10m": 311,
                        "windGustSpeed10m": 5.99,
                        "max10mWindGust": 5.99,
                        "visibility": 30149,
                        "screenRelativeHumidity": 34.67,
                        "mslp": 103063,
                        "uvIndex": 5,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T16:00Z",
                        "screenTemperature": 27.45,
                        "maxScreenAirTemp": 27.48,
                        "minScreenAirTemp": 27.33,
                        "screenDewPointTemperature": 9.91,
                        "feelsLikeTemperature": 25.97,
                        "windSpeed10m": 3.58,
                        "windDirectionFrom10m": 315,
                        "windGustSpeed10m": 6.52,
                        "max10mWindGust": 6.52,
                        "visibility": 30053,
                        "screenRelativeHumidity": 33.58,
                        "mslp": 103013,
                        "uvIndex": 3,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T17:00Z",
                        "screenTemperature": 27.3,
                        "maxScreenAirTemp": 27.45,
                        "minScreenAirTemp": 27.29,
                        "screenDewPointTemperature": 9.71,
                        "feelsLikeTemperature": 25.5,
                        "windSpeed10m": 4.01,
                        "windDirectionFrom10m": 319,
                        "windGustSpeed10m": 7.27,
                        "max10mWindGust": 7.27,
                        "visibility": 29390,
                        "screenRelativeHumidity": 33.46,
                        "mslp": 102984,
                        "uvIndex": 2,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T18:00Z",
                        "screenTemperature": 26.85,
                        "maxScreenAirTemp": 27.3,
                        "minScreenAirTemp": 26.82,
                        "screenDewPointTemperature": 9.88,
                        "feelsLikeTemperature": 24.98,
                        "windSpeed10m": 4.14,
                        "windDirectionFrom10m": 322,
                        "windGustSpeed10m": 7.49,
                        "max10mWindGust": 7.49,
                        "visibility": 28683,
                        "screenRelativeHumidity": 34.63,
                        "mslp": 102954,
                        "uvIndex": 1,
                        "significantWeatherCode": 3,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T19:00Z",
                        "screenTemperature": 25.86,
                        "maxScreenAirTemp": 26.85,
                        "minScreenAirTemp": 25.84,
                        "screenDewPointTemperature": 10.06,
                        "feelsLikeTemperature": 24.16,
                        "windSpeed10m": 3.84,
                        "windDirectionFrom10m": 329,
                        "windGustSpeed10m": 6.89,
                        "max10mWindGust": 7.46,
                        "visibility": 29953,
                        "screenRelativeHumidity": 37.44,
                        "mslp": 102947,
                        "uvIndex": 1,
                        "significantWeatherCode": 3,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T20:00Z",
                        "screenTemperature": 24.61,
                        "maxScreenAirTemp": 25.86,
                        "minScreenAirTemp": 24.61,
                        "screenDewPointTemperature": 10.37,
                        "feelsLikeTemperature": 22.78,
                        "windSpeed10m": 4.06,
                        "windDirectionFrom10m": 341,
                        "windGustSpeed10m": 7.3,
                        "max10mWindGust": 7.86,
                        "visibility": 29124,
                        "screenRelativeHumidity": 41.19,
                        "mslp": 102977,
                        "uvIndex": 1,
                        "significantWeatherCode": 3,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T21:00Z",
                        "screenTemperature": 23.08,
                        "maxScreenAirTemp": 24.61,
                        "minScreenAirTemp": 23.06,
                        "screenDewPointTemperature": 10.74,
                        "feelsLikeTemperature": 21.43,
                        "windSpeed10m": 3.77,
                        "windDirectionFrom10m": 348,
                        "windGustSpeed10m": 6.86,
                        "max10mWindGust": 8.0,
                        "visibility": 29209,
                        "screenRelativeHumidity": 46.1,
                        "mslp": 103004,
                        "uvIndex": 0,
                        "significantWeatherCode": 2,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T22:00Z",
                        "screenTemperature": 21.87,
                        "maxScreenAirTemp": 23.08,
                        "minScreenAirTemp": 21.85,
                        "screenDewPointTemperature": 11.13,
                        "feelsLikeTemperature": 20.09,
                        "windSpeed10m": 4.04,
                        "windDirectionFrom10m": 345,
                        "windGustSpeed10m": 7.43,
                        "max10mWindGust": 8.52,
                        "visibility": 28647,
                        "screenRelativeHumidity": 50.81,
                        "mslp": 103017,
                        "uvIndex": 0,
                        "significantWeatherCode": 0,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-08T23:00Z",
                        "screenTemperature": 20.65,
                        "maxScreenAirTemp": 21.87,
                        "minScreenAirTemp": 20.64,
                        "screenDewPointTemperature": 11.45,
                        "feelsLikeTemperature": 18.93,
                        "windSpeed10m": 4.01,
                        "windDirectionFrom10m": 345,
                        "windGustSpeed10m": 7.31,
                        "max10mWindGust": 8.66,
                        "visibility": 27948,
                        "screenRelativeHumidity": 55.84,
                        "mslp": 103030,
                        "uvIndex": 0,
                        "significantWeatherCode": 0,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T00:00Z",
                        "screenTemperature": 19.58,
                        "maxScreenAirTemp": 20.65,
                        "minScreenAirTemp": 19.57,
                        "screenDewPointTemperature": 11.59,
                        "feelsLikeTemperature": 17.98,
                        "windSpeed10m": 3.85,
                        "windDirectionFrom10m": 341,
                        "windGustSpeed10m": 7.05,
                        "max10mWindGust": 8.11,
                        "visibility": 27531,
                        "screenRelativeHumidity": 59.97,
                        "mslp": 103033,
                        "uvIndex": 0,
                        "significantWeatherCode": 2,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 1
                    },
                    {
                        "time": "2022-07-09T01:00Z",
                        "screenTemperature": 18.51,
                        "maxScreenAirTemp": 19.58,
                        "minScreenAirTemp": 18.49,
                        "screenDewPointTemperature": 11.8,
                        "feelsLikeTemperature": 17.17,
                        "windSpeed10m": 3.62,
                        "windDirectionFrom10m": 342,
                        "windGustSpeed10m": 6.71,
                        "max10mWindGust": 7.85,
                        "visibility": 27405,
                        "screenRelativeHumidity": 65.23,
                        "mslp": 103033,
                        "uvIndex": 0,
                        "significantWeatherCode": 0,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T02:00Z",
                        "screenTemperature": 17.54,
                        "maxScreenAirTemp": 18.51,
                        "minScreenAirTemp": 17.51,
                        "screenDewPointTemperature": 11.96,
                        "feelsLikeTemperature": 16.34,
                        "windSpeed10m": 3.51,
                        "windDirectionFrom10m": 343,
                        "windGustSpeed10m": 6.56,
                        "max10mWindGust": 7.58,
                        "visibility": 25363,
                        "screenRelativeHumidity": 70.09,
                        "mslp": 103023,
                        "uvIndex": 0,
                        "significantWeatherCode": 0,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T03:00Z",
                        "screenTemperature": 16.65,
                        "maxScreenAirTemp": 17.54,
                        "minScreenAirTemp": 16.64,
                        "screenDewPointTemperature": 12.14,
                        "feelsLikeTemperature": 15.74,
                        "windSpeed10m": 3.12,
                        "windDirectionFrom10m": 343,
                        "windGustSpeed10m": 5.87,
                        "max10mWindGust": 7.42,
                        "visibility": 24005,
                        "screenRelativeHumidity": 74.91,
                        "mslp": 103013,
                        "uvIndex": 0,
                        "significantWeatherCode": 0,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T04:00Z",
                        "screenTemperature": 16.45,
                        "maxScreenAirTemp": 16.65,
                        "minScreenAirTemp": 16.44,
                        "screenDewPointTemperature": 12.23,
                        "feelsLikeTemperature": 15.62,
                        "windSpeed10m": 3.02,
                        "windDirectionFrom10m": 343,
                        "windGustSpeed10m": 5.89,
                        "max10mWindGust": 7.01,
                        "visibility": 23134,
                        "screenRelativeHumidity": 76.23,
                        "mslp": 103020,
                        "uvIndex": 1,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T05:00Z",
                        "screenTemperature": 16.42,
                        "maxScreenAirTemp": 16.45,
                        "minScreenAirTemp": 16.39,
                        "screenDewPointTemperature": 12.33,
                        "feelsLikeTemperature": 15.63,
                        "windSpeed10m": 2.98,
                        "windDirectionFrom10m": 341,
                        "windGustSpeed10m": 5.87,
                        "max10mWindGust": 6.33,
                        "visibility": 22202,
                        "screenRelativeHumidity": 76.87,
                        "mslp": 103033,
                        "uvIndex": 1,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T06:00Z",
                        "screenTemperature": 16.66,
                        "maxScreenAirTemp": 16.85,
                        "minScreenAirTemp": 16.42,
                        "screenDewPointTemperature": 12.37,
                        "feelsLikeTemperature": 15.83,
                        "windSpeed10m": 3.08,
                        "windDirectionFrom10m": 343,
                        "windGustSpeed10m": 5.92,
                        "max10mWindGust": 6.45,
                        "visibility": 22194,
                        "screenRelativeHumidity": 75.94,
                        "mslp": 103053,
                        "uvIndex": 1,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T07:00Z",
                        "screenTemperature": 17.65,
                        "maxScreenAirTemp": 17.65,
                        "minScreenAirTemp": 16.66,
                        "screenDewPointTemperature": 11.88,
                        "feelsLikeTemperature": 16.46,
                        "windSpeed10m": 3.49,
                        "windDirectionFrom10m": 343,
                        "windGustSpeed10m": 6.68,
                        "max10mWindGust": 6.68,
                        "visibility": 24627,
                        "screenRelativeHumidity": 69.38,
                        "mslp": 103055,
                        "uvIndex": 3,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T08:00Z",
                        "screenTemperature": 18.67,
                        "maxScreenAirTemp": 18.69,
                        "minScreenAirTemp": 17.65,
                        "screenDewPointTemperature": 11.38,
                        "feelsLikeTemperature": 17.25,
                        "windSpeed10m": 3.64,
                        "windDirectionFrom10m": 340,
                        "windGustSpeed10m": 6.93,
                        "max10mWindGust": 6.93,
                        "visibility": 27626,
                        "screenRelativeHumidity": 62.99,
                        "mslp": 103050,
                        "uvIndex": 4,
                        "significantWeatherCode": 3,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T09:00Z",
                        "screenTemperature": 19.66,
                        "maxScreenAirTemp": 19.68,
                        "minScreenAirTemp": 18.67,
                        "screenDewPointTemperature": 11.0,
                        "feelsLikeTemperature": 17.94,
                        "windSpeed10m": 3.88,
                        "windDirectionFrom10m": 342,
                        "windGustSpeed10m": 7.4,
                        "max10mWindGust": 7.4,
                        "visibility": 27882,
                        "screenRelativeHumidity": 57.53,
                        "mslp": 103047,
                        "uvIndex": 5,
                        "significantWeatherCode": 7,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 3
                    },
                    {
                        "time": "2022-07-09T10:00Z",
                        "screenTemperature": 20.75,
                        "maxScreenAirTemp": 20.77,
                        "minScreenAirTemp": 19.66,
                        "screenDewPointTemperature": 10.01,
                        "feelsLikeTemperature": 18.81,
                        "windSpeed10m": 3.96,
                        "windDirectionFrom10m": 338,
                        "windGustSpeed10m": 7.62,
                        "max10mWindGust": 7.62,
                        "visibility": 29066,
                        "screenRelativeHumidity": 50.69,
                        "mslp": 103025,
                        "uvIndex": 6,
                        "significantWeatherCode": 3,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T11:00Z",
                        "screenTemperature": 21.83,
                        "maxScreenAirTemp": 21.86,
                        "minScreenAirTemp": 20.75,
                        "screenDewPointTemperature": 8.7,
                        "feelsLikeTemperature": 19.9,
                        "windSpeed10m": 3.67,
                        "windDirectionFrom10m": 337,
                        "windGustSpeed10m": 7.21,
                        "max10mWindGust": 7.21,
                        "visibility": 31693,
                        "screenRelativeHumidity": 43.56,
                        "mslp": 103005,
                        "uvIndex": 7,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T12:00Z",
                        "screenTemperature": 22.9,
                        "maxScreenAirTemp": 22.93,
                        "minScreenAirTemp": 21.83,
                        "screenDewPointTemperature": 7.81,
                        "feelsLikeTemperature": 20.92,
                        "windSpeed10m": 3.59,
                        "windDirectionFrom10m": 336,
                        "windGustSpeed10m": 7.19,
                        "max10mWindGust": 7.19,
                        "visibility": 31967,
                        "screenRelativeHumidity": 38.25,
                        "mslp": 102990,
                        "uvIndex": 8,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T13:00Z",
                        "screenTemperature": 23.69,
                        "maxScreenAirTemp": 23.7,
                        "minScreenAirTemp": 22.9,
                        "screenDewPointTemperature": 7.27,
                        "feelsLikeTemperature": 21.6,
                        "windSpeed10m": 3.7,
                        "windDirectionFrom10m": 344,
                        "windGustSpeed10m": 7.39,
                        "max10mWindGust": 7.39,
                        "visibility": 32384,
                        "screenRelativeHumidity": 35.36,
                        "mslp": 102960,
                        "uvIndex": 7,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T14:00Z",
                        "screenTemperature": 24.35,
                        "maxScreenAirTemp": 24.37,
                        "minScreenAirTemp": 23.69,
                        "screenDewPointTemperature": 6.85,
                        "feelsLikeTemperature": 22.24,
                        "windSpeed10m": 3.67,
                        "windDirectionFrom10m": 350,
                        "windGustSpeed10m": 7.36,
                        "max10mWindGust": 7.36,
                        "visibility": 35667,
                        "screenRelativeHumidity": 33.08,
                        "mslp": 102925,
                        "uvIndex": 6,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T15:00Z",
                        "screenTemperature": 24.92,
                        "maxScreenAirTemp": 24.94,
                        "minScreenAirTemp": 24.35,
                        "screenDewPointTemperature": 6.24,
                        "feelsLikeTemperature": 22.76,
                        "windSpeed10m": 3.67,
                        "windDirectionFrom10m": 356,
                        "windGustSpeed10m": 7.35,
                        "max10mWindGust": 7.35,
                        "visibility": 36499,
                        "screenRelativeHumidity": 30.67,
                        "mslp": 102893,
                        "uvIndex": 5,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T16:00Z",
                        "screenTemperature": 24.82,
                        "maxScreenAirTemp": 24.92,
                        "minScreenAirTemp": 24.82,
                        "screenDewPointTemperature": 6.44,
                        "feelsLikeTemperature": 22.62,
                        "windSpeed10m": 3.78,
                        "windDirectionFrom10m": 5,
                        "windGustSpeed10m": 7.65,
                        "max10mWindGust": 7.65,
                        "visibility": 36339,
                        "screenRelativeHumidity": 31.5,
                        "mslp": 102871,
                        "uvIndex": 4,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T17:00Z",
                        "screenTemperature": 24.65,
                        "maxScreenAirTemp": 24.82,
                        "minScreenAirTemp": 24.64,
                        "screenDewPointTemperature": 6.78,
                        "feelsLikeTemperature": 22.37,
                        "windSpeed10m": 3.94,
                        "windDirectionFrom10m": 14,
                        "windGustSpeed10m": 7.8,
                        "max10mWindGust": 7.8,
                        "visibility": 35719,
                        "screenRelativeHumidity": 32.48,
                        "mslp": 102872,
                        "uvIndex": 2,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T18:00Z",
                        "screenTemperature": 23.5,
                        "maxScreenAirTemp": 24.65,
                        "minScreenAirTemp": 23.38,
                        "screenDewPointTemperature": 8.98,
                        "feelsLikeTemperature": 21.21,
                        "windSpeed10m": 4.37,
                        "windDirectionFrom10m": 44,
                        "windGustSpeed10m": 8.11,
                        "max10mWindGust": 8.3,
                        "visibility": 33713,
                        "screenRelativeHumidity": 39.9,
                        "mslp": 102883,
                        "uvIndex": 1,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T19:00Z",
                        "screenTemperature": 21.8,
                        "maxScreenAirTemp": 23.5,
                        "minScreenAirTemp": 21.8,
                        "screenDewPointTemperature": 9.99,
                        "feelsLikeTemperature": 19.8,
                        "windSpeed10m": 4.13,
                        "windDirectionFrom10m": 59,
                        "windGustSpeed10m": 7.63,
                        "max10mWindGust": 8.4,
                        "visibility": 34172,
                        "screenRelativeHumidity": 48.68,
                        "mslp": 102916,
                        "uvIndex": 1,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T20:00Z",
                        "screenTemperature": 20.22,
                        "maxScreenAirTemp": 21.8,
                        "minScreenAirTemp": 20.22,
                        "screenDewPointTemperature": 11.01,
                        "feelsLikeTemperature": 18.62,
                        "windSpeed10m": 3.81,
                        "windDirectionFrom10m": 78,
                        "windGustSpeed10m": 7.01,
                        "max10mWindGust": 7.9,
                        "visibility": 29432,
                        "screenRelativeHumidity": 57.39,
                        "mslp": 102948,
                        "uvIndex": 1,
                        "significantWeatherCode": 1,
                        "precipitationRate": 0,
                        "totalPrecipAmount": 0,
                        "totalSnowAmount": 0,
                        "probOfPrecipitation": 0
                    },
                    {
                        "time": "2022-07-09T21:00Z",
                        "screenTemperature": 18.8,
                        "screenDewPointTemperature": 11.95,
                        "feelsLikeTemperature": 17.6,
                        "windSpeed10m": 3.45,
                        "windDirectionFrom10m": 101,
                        "windGustSpeed10m": 6.35,
                        "visibility": 29819,
                        "screenRelativeHumidity": 65.38,
                        "mslp": 102988,
                        "uvIndex": 0,
                        "significantWeatherCode": 0,
                        "precipitationRate": 0,
                        "probOfPrecipitation": 0
                    }
                ]
            }
        }
    ],
    "parameters": [
        {
            "totalSnowAmount": {
                "type": "Parameter",
                "description": "Total Snow Amount Over Previous Hour",
                "unit": {
                    "label": "millimetres",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "mm"
                    }
                }
            },
            "screenTemperature": {
                "type": "Parameter",
                "description": "Screen Air Temperature",
                "unit": {
                    "label": "degrees Celsius",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "Cel"
                    }
                }
            },
            "visibility": {
                "type": "Parameter",
                "description": "Visibility",
                "unit": {
                    "label": "metres",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "m"
                    }
                }
            },
            "windDirectionFrom10m": {
                "type": "Parameter",
                "description": "10m Wind From Direction",
                "unit": {
                    "label": "degrees",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "deg"
                    }
                }
            },
            "precipitationRate": {
                "type": "Parameter",
                "description": "Precipitation Rate",
                "unit": {
                    "label": "millimetres per hour",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "mm/h"
                    }
                }
            },
            "maxScreenAirTemp": {
                "type": "Parameter",
                "description": "Maximum Screen Air Temperature Over Previous Hour",
                "unit": {
                    "label": "degrees Celsius",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "Cel"
                    }
                }
            },
            "feelsLikeTemperature": {
                "type": "Parameter",
                "description": "Feels Like Temperature",
                "unit": {
                    "label": "degrees Celsius",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "Cel"
                    }
                }
            },
            "screenDewPointTemperature": {
                "type": "Parameter",
                "description": "Screen Dew Point Temperature",
                "unit": {
                    "label": "degrees Celsius",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "Cel"
                    }
                }
            },
            "screenRelativeHumidity": {
                "type": "Parameter",
                "description": "Screen Relative Humidity",
                "unit": {
                    "label": "percentage",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "%"
                    }
                }
            },
            "windSpeed10m": {
                "type": "Parameter",
                "description": "10m Wind Speed",
                "unit": {
                    "label": "metres per second",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "m/s"
                    }
                }
            },
            "probOfPrecipitation": {
                "type": "Parameter",
                "description": "Probability of Precipitation",
                "unit": {
                    "label": "percentage",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "%"
                    }
                }
            },
            "max10mWindGust": {
                "type": "Parameter",
                "description": "Maximum 10m Wind Gust Speed Over Previous Hour",
                "unit": {
                    "label": "metres per second",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "m/s"
                    }
                }
            },
            "significantWeatherCode": {
                "type": "Parameter",
                "description": "Significant Weather Code",
                "unit": {
                    "label": "dimensionless",
                    "symbol": {
                        "value": "https://metoffice.apiconnect.ibmcloud.com/metoffice/production/",
                        "type": "1"
                    }
                }
            },
            "minScreenAirTemp": {
                "type": "Parameter",
                "description": "Minimum Screen Air Temperature Over Previous Hour",
                "unit": {
                    "label": "degrees Celsius",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "Cel"
                    }
                }
            },
            "totalPrecipAmount": {
                "type": "Parameter",
                "description": "Total Precipitation Amount Over Previous Hour",
                "unit": {
                    "label": "millimetres",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "mm"
                    }
                }
            },
            "mslp": {
                "type": "Parameter",
                "description": "Mean Sea Level Pressure",
                "unit": {
                    "label": "pascals",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "Pa"
                    }
                }
            },
            "windGustSpeed10m": {
                "type": "Parameter",
                "description": "10m Wind Gust Speed",
                "unit": {
                    "label": "metres per second",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "m/s"
                    }
                }
            },
            "uvIndex": {
                "type": "Parameter",
                "description": "UV Index",
                "unit": {
                    "label": "dimensionless",
                    "symbol": {
                        "value": "http://www.opengis.net/def/uom/UCUM/",
                        "type": "1"
                    }
                }
            }
        }
    ]
}
"""
    
}
